---
title: "Neighborhood Typologies Workflow"
output: html_notebook
---

```{r load dependencies}
source('proportion_typology.R')
source('neighborhood_clustering.R')
source('Location_Quotient.R')
library(readstata13)
library(haven) 
library(betareg)
library(tidyverse)
```

```{r helper function to load chetty data}
load_chetty <- function(){
  if(!file.exists('data/chetty.csv')){ # if we don't have a chetty file
    chetty_full <- read_csv('data/tract_outcomes.zip') # load the fully Atlas
    # chetty pre-process
    # make TRTID10 var
    # select some variables
    chetty <- chetty_full %>%  # take the atlas
      mutate(state = str_extract(str_c('0', state),'\\d\\d$'), # make a tract id var
             county = str_extract(str_c('000', county),'\\d{3}$'),
             tract = str_extract(str_c('00000', tract),'\\d{6}$'),
             TRTID10 = as.numeric(str_c(state, county, tract))) %>% 
      # select the outcomes of interest
      select(state, county, tract, TRTID10, jail_white_pooled_mean, jail_white_pooled_mean_se, jail_black_pooled_mean, jail_black_pooled_mean_se, jail_asian_pooled_mean, jail_asian_pooled_mean_se, jail_hisp_pooled_mean, jail_hisp_pooled_mean_se, kfr_top01_pooled_pooled_mean, kfr_top01_pooled_pooled_mean_se, kfr_top01_white_pooled_mean, kfr_top01_white_pooled_mean_se, kfr_top01_black_pooled_mean, kfr_top01_black_pooled_mean_se, kfr_top01_asian_pooled_mean, kfr_top01_asian_pooled_mean_se, kfr_top01_hisp_pooled_mean, kfr_top01_hisp_pooled_mean_se,kfr_top20_pooled_pooled_mean, kfr_top20_pooled_pooled_mean_se, kfr_top20_white_pooled_mean, kfr_top20_white_pooled_mean_se, kfr_top20_black_pooled_mean, kfr_top20_black_pooled_mean_se, kfr_top20_asian_pooled_mean, kfr_top20_asian_pooled_mean_se, kfr_top20_hisp_pooled_mean, kfr_top20_hisp_pooled_mean_se, kfr_white_pooled_mean, kfr_white_pooled_mean_se, kfr_black_pooled_mean, kfr_black_pooled_mean_se, kfr_asian_pooled_mean, kfr_asian_pooled_mean_se, kfr_hisp_pooled_mean, kfr_hisp_pooled_mean_se, teenbrth_white_female_mean, teenbrth_white_female_mean_se, teenbrth_black_female_mean, teenbrth_black_female_mean_se, teenbrth_asian_female_mean, teenbrth_asian_female_mean_se, teenbrth_hisp_female_mean, teenbrth_hisp_female_mean_se)
    # write a csv
    write_csv(chetty, 'data/chetty.csv')
  } else { # if we do have a chetty file, load it
  chetty <- read_csv('data/chetty.csv')
  }
  return(chetty)
}
```


```{r prepare for analysis}
if(!file.exists('data/df_full.csv')){ # if we don't have saved data
  df <- read_csv("data/LTDB_Std_1980_fullcount.csv") # get the 1980 census data
  chetty <- load_chetty() # load a reduced version of chetty's atlas
  nh_cluster <- nh_cluster(df) # run Hannah's neighborhood clustering algo and join to census
  df_full <- full_join(df, nh_cluster, by = 'TRTID10')
  race_typology <- race_typology(df) # run Ian's neighborhood typology and joing to census
  df_full <- full_join(df_full, race_typology, by = 'TRTID10')
  l_quotient <- l_quotient(df) # run Shihao's location quotient algo and joing to census
  df_full <- inner_join(df_full, l_quotient, by = 'TRTID10')
  df_full <- full_join(df_full, chetty, by = 'TRTID10') # join all with census
  df_full %>% write_csv('data/df_full.csv')  # and write to csv
} else{ # otherwise read from file
  df_full <- read_csv('data/df_full.csv')
}
```


```{r modeling teen births}
model <- glm(dv1 ~ ian + covariates?)
```


```{r modeling incarceration}
model <- glm(dv1 ~ ian + covariates)
```

Modeling the probability of Black children born/living in the tract in 1980 reaching the top 20% of incomes in 2010 based on our typologies and neighborhood racial proportions.
```{r modeling probability of reaching top 20%}
# make a df just for this IV
top_20 <- df_full %>% 
  select(starts_with('kfr_top20'), starts_with('prop'), ends_with('dmmy'), starts_with('LQ'), contains('type')) %>%
  mutate_all(funs(replace(., is.na(.), 0))) %>% filter(kfr_top20_pooled_pooled_mean >0)

#fit models for proportion, ntype, location q, and clustering
model_prop <- betareg(kfr_top20_pooled_pooled_mean ~ prop.nhwht80 + prop.nhblk80 + prop.asian80 + prop.hisp80, data = top_20)

model_ntype <- betareg(kfr_top20_pooled_pooled_mean ~ collapsed_type, data = top_20)

# this one sometimes doesn't converge when I use the whole set, so I use a sample
model_lq <- betareg(kfr_top20_pooled_pooled_mean ~ LQ_white_80 + LQ_black_80 + LQ_asian_80 + LQ_native_80, data = top_20 %>% sample_n(10000))

model_cluster <- betareg(kfr_top20_pooled_pooled_mean ~ wht.clst.dmmy + blk.clst.dmmy + as.clst.dmmy + hisp.clst.dmmy, data = top_20)
```

Actual vs predicted plots to check in-sample fit
```{r actual vs predicted plots}
bins = 40 # set the number of bins
 # function which takes a model and spits out a dataframe formatted to make an avp plot
prep_avp_df <- function(model, bins, model_name){
  # grab the model predictions and actual values
  inter_df <- tibble(actual = model$y, predicted = model$fitted.values) %>% 
    # bin the values
    mutate(x_bins = ntile(actual, bins), 
           y_bins =ntile(predicted, bins))
  # group by bins and return averages
  return(bind_cols(inter_df %>% group_by(x_bins) %>% summarise(actual = mean(actual)),
            inter_df %>% group_by(y_bins) %>% summarise(predicted = mean(actual))) %>% mutate(model = model_name))
  
}
# row bind the results for each model
plot_df <- bind_rows(prep_avp_df(model_cluster, bins, 'cluster'),
          prep_avp_df(model_lq, bins, 'location quotient'),
          prep_avp_df(model_ntype, bins, 'neighborhood type'),
          prep_avp_df(model_prop, bins, 'racial proportion'))
# plot comparison
ggplot(plot_df, aes(x = predicted, y = actual, color = model))+
    geom_point(alpha = .5)+
    geom_abline(aes(slope = 1, intercept = 0), color = 'red')
```


Goodness of fit tests

```{r}
make_cool_visualization(model, ian)
```


